{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mqttnio\/mqtterror\/connectionerror(_:)"]}],"hierarchy":{"paths":[["doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO","doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/connectionError(_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"connectionError","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7MQTTNIO9MQTTErrorO21ConnectionReturnValueO","text":"ConnectionReturnValue","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Case","modules":[{"name":"MQTTNIO"}],"externalID":"s:7MQTTNIO9MQTTErrorO15connectionErroryA2C21ConnectionReturnValueOcACmF","title":"MQTTError.connectionError(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"We received an unsuccessful connection return value","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7MQTTNIO9MQTTErrorO21ConnectionReturnValueO","identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/ConnectionReturnValue","text":"ConnectionReturnValue"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO/MQTTError/ConnectionReturnValue":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConnectionReturnValue"}],"type":"topic","navigatorTitle":[{"text":"ConnectionReturnValue","kind":"identifier"}],"role":"symbol","url":"\/documentation\/mqttnio\/mqtterror\/connectionreturnvalue","kind":"symbol","identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/ConnectionReturnValue","title":"MQTTError.ConnectionReturnValue","abstract":[{"type":"text","text":"Value returned in connection error"}]},"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO/MQTTError":{"identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError","abstract":[{"type":"text","text":"MQTTClient errors"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MQTTError"}],"kind":"symbol","role":"symbol","title":"MQTTError","url":"\/documentation\/mqttnio\/mqtterror","navigatorTitle":[{"text":"MQTTError","kind":"identifier"}],"type":"topic"},"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO/MQTTError/connectionError(_:)":{"role":"symbol","type":"topic","title":"MQTTError.connectionError(_:)","identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/connectionError(_:)","url":"\/documentation\/mqttnio\/mqtterror\/connectionerror(_:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7MQTTNIO9MQTTErrorO21ConnectionReturnValueO","kind":"typeIdentifier","text":"ConnectionReturnValue"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"text":"We received an unsuccessful connection return value","type":"text"}]},"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO":{"url":"\/documentation\/mqttnio","role":"collection","title":"MQTTNIO","abstract":[{"type":"text","text":"A Swift NIO based MQTT client"}],"identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO","kind":"symbol","type":"topic"}}}