{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/ConnectionReturnValue","preciseIdentifier":"s:7MQTTNIO9MQTTErrorO21ConnectionReturnValueO","text":"ConnectionReturnValue"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/mqttnio\/mqtterror\/connectionerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/connectionError(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"We received an unsuccessful connection return value"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ConnectionReturnValue","preciseIdentifier":"s:7MQTTNIO9MQTTErrorO21ConnectionReturnValueO"},{"kind":"text","text":")"}],"title":"MQTTError.connectionError(_:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:7MQTTNIO9MQTTErrorO15connectionErroryA2C21ConnectionReturnValueOcACmF","modules":[{"name":"MQTTNIO"}]},"hierarchy":{"paths":[["doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO","doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError"]]},"references":{"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO":{"role":"collection","title":"MQTTNIO","abstract":[{"type":"text","text":"A Swift NIO based MQTT client"}],"identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO","kind":"symbol","type":"topic","url":"\/documentation\/mqttnio"},"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO/MQTTError":{"role":"symbol","title":"MQTTError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MQTTError"}],"abstract":[{"type":"text","text":"MQTTClient errors"}],"identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MQTTError"}],"url":"\/documentation\/mqttnio\/mqtterror"},"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO/MQTTError/ConnectionReturnValue":{"role":"symbol","title":"MQTTError.ConnectionReturnValue","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionReturnValue"}],"abstract":[{"type":"text","text":"Value returned in connection error"}],"identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/ConnectionReturnValue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConnectionReturnValue"}],"url":"\/documentation\/mqttnio\/mqtterror\/connectionreturnvalue"},"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO/MQTTError/connectionError(_:)":{"role":"symbol","title":"MQTTError.connectionError(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"connectionError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ConnectionReturnValue","preciseIdentifier":"s:7MQTTNIO9MQTTErrorO21ConnectionReturnValueO"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"We received an unsuccessful connection return value"}],"identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/connectionError(_:)","kind":"symbol","type":"topic","url":"\/documentation\/mqttnio\/mqtterror\/connectionerror(_:)"}}}