{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/retrySend"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/mqttnio\/mqtterror\/retrysend"]}],"hierarchy":{"paths":[["doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO","doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError"]]},"metadata":{"modules":[{"name":"MQTTNIO"}],"roleHeading":"Case","title":"MQTTError.retrySend","externalID":"s:7MQTTNIO9MQTTErrorO9retrySendyA2CmF","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"retrySend","kind":"identifier"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Internal error, used to get the client to retry sending","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrySend"}],"platforms":["macOS"]}]}],"references":{"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO":{"url":"\/documentation\/mqttnio","role":"collection","title":"MQTTNIO","abstract":[{"type":"text","text":"A Swift NIO based MQTT client"}],"identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO","kind":"symbol","type":"topic"},"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO/MQTTError":{"identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError","abstract":[{"type":"text","text":"MQTTClient errors"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MQTTError"}],"kind":"symbol","role":"symbol","title":"MQTTError","url":"\/documentation\/mqttnio\/mqtterror","navigatorTitle":[{"text":"MQTTError","kind":"identifier"}],"type":"topic"},"doc://org.swift-server-community.mqtt-nio/documentation/MQTTNIO/MQTTError/retrySend":{"title":"MQTTError.retrySend","abstract":[{"type":"text","text":"Internal error, used to get the client to retry sending"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrySend"}],"identifier":"doc:\/\/org.swift-server-community.mqtt-nio\/documentation\/MQTTNIO\/MQTTError\/retrySend","kind":"symbol","url":"\/documentation\/mqttnio\/mqtterror\/retrysend"}}}